"""Create college_partners table

Revision ID: 07a516e880d6
Revises: b2e7ad1fa3b9
Create Date: 2026-06-30 13:27:28.210067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a516e880d6'
down_revision = 'b2e7ad1fa3b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college_partners',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('college_partners')
    # ### end Alembic commands ###
