"""Update documents table

Revision ID: c0763dcc9abd
Revises: 4ae0483fd167
Create Date: 2026-06-30 19:06:12.837289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0763dcc9abd'
down_revision = '4ae0483fd167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stored_file_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('file_size')
        batch_op.drop_column('stored_file_name')

    # ### end Alembic commands ###
